name: Release Extension to Chrome Web Store
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  release:
    name: Upload & Publish to Chrome Web Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip extension
        run: |
          zip -r src.zip src/

      - name: Upload to Chrome Web Store
        uses: browser-actions/release-chrome-extension@latest
        with:
          extension-id: "eanhlljpacpbggaiijocfoapjbofdbfm"
          extension-path: "src.zip"
          oauth-client-id: ${{ secrets.OAUTH_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
          oauth-refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }}
